models/Post.php
<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "post".
 *
 * @property int $idpost
 * @property string $title
 * @property string $content
 * @property string $date
 * @property string $username
 * @property string $image
 * 
 *
 * @property Account $username0
 */
class Post extends \yii\db\ActiveRecord
{

    const STATUS_DRAFT = "draft";
    const STATUS_PUBLISH = "publish";

    public $file_image;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'content', 'username', 'idcategory'], 'required'],
            [['title', 'content', 'image', 'status'], 'string'],
            [['date', 'date_publish'], 'safe'],
            [['username'], 'string', 'max' => 45],
            [['username'], 'exist', 'skipOnError' => true, 'targetClass' => Account::class, 'targetAttribute' => ['username' => 'username']],
            [['file_image'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg, gif'],
            [['status'], 'default', 'value' => self::STATUS_DRAFT],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'idpost' => 'Idpost',
            'title' => 'Title',
            'content' => 'Content',
            'date' => 'Date',
            'username' => 'Username',
            'image' => 'Cover',
            'idcategory' => 'Category',
            'status' => 'Status',
            'date_publish' => 'Date Publish'
        ];
    }

    /**
     * Gets query for [[Username0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
{
    return $this->hasOne(User::class, ['id' => 'user_id']);
}

    public function getCategory()
    {
        return $this->hasOne(Category::class, ['idcategory' => 'idcategory']);
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use app\models\Post;
use app\models\SearchPost;
use app\models\User;
use app\models\Category;
use yii\web\UploadedFile;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\AccessRule;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\ForbiddenHttpException;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'ruleConfig' => [
                    'class' => AccessRule::className()
                ],
                'rules' => [
                    [
                        // 'actions' => ['index', 'view', 'create'],
                        'controllers' => ['post'],
                        'allow' => true,
                        'matchCallback' => function($rule, $action) {
                            return User::getIsAdmin();
                        }
                    ],
                    [
                        'actions' => ['index', 'view', 'create', 'approve'],
                        // 'controllers' => ['post'],
                        'allow' => true,
                        'matchCallback' => function($rule, $action) {
                            return User::getIsAuthor();
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new SearchPost();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    //     $categories = Category::find()->all();
    //     return $this->render('ListCategory', [
    //         'categories' => $categories,
    //     ]);
    }


    // UNTUK MENAMPILKAN INDEX UNTUK ADMIN APPROVE 
    public function actionIndexApprove()
    {
        
        $query = Post::find();
        
         // Query untuk mengambil data post
         $query = Post::find();
         
             $query->andWhere(['status' => 'Draft']);

         // Data provider untuk digunakan di view
         $dataProvider = new ActiveDataProvider([
             'query' => $query,
         ]);
        return $this->render('approve', [
            'dataProvider' => $dataProvider,
        ]);
    }


    // UNTUK MENGAPPROVE SALAH SATU BLOG
    public function actionApprove($idpost)
    {
        $model = $this->findModel($idpost);

        if (!User::getIsAdmin()) {
            throw new ForbiddenHttpException('Kamu Tidak Bisa Mengakses Aksi Ini');
        }
        
        $model->status = 'publish';
        if ($model->save()) {
            Yii::$app->session->setFlash('success', 'Post has been published.');
        } else {
            Yii::$app->session->setFlash('error', 'Failed to approve the post.');
        }

        return $this->redirect(['index-approve']);
    }


    public function actionCategory($idcategory)
    {
        $category = Category::findOne($idcategory);

        if (!$category) {
            throw new \yii\web\NotFoundHttpException('Halaman Request Tidak Ada');
        }  

        $query = $category->getPosts();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        return $this->render('category', [
            'category' => $category,
            'dataProvider' => $dataProvider,
        ]);
    }
    

    /**
     * Displays a single Post model.
     * @param int $idpost Idpost
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($idpost)
    {
        return $this->render('view', [
            'model' => $this->findModel($idpost),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Post();
        

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {  

                $model->file_image = UploadedFile::getInstance($model, 'file_image');
                
            //    echo '<pre>';
            // print_r($model);
            // die;

            if($model->file_image){
                
                $img = uniqid('img_cover', true);
                $saveTo = 'uploads/cover/'.$img.'.'.$model->file_image->extension;
                if ($model->file_image->saveAs($saveTo, false));

                $model->image = $saveTo;
            }
            
                $model->save();
                return $this->redirect(['view', 'idpost' => $model->idpost]);
            }
        } else {
            $model->loadDefaultValues();
        }

        if (!Yii::$app->user->isGuest) {
            $model -> username = Yii::$app->user->identity->username;
        }
 
        $model -> date = date('Y-m-d H:i:s');

        $model -> date_publish = date('Y-m-d');
        
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $idpost Idpost
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($idpost)
    {
        $model = $this->findModel($idpost);

        if ($this->request->isPost && $model->load($this->request->post())) {

            $model->file_image = UploadedFile::getInstance($model, 'file_image');
            // echo '<pre>';
            // print_r($model);
            // die;

            if($model->file_image){
                
                $img = uniqid('img_cover', true);
                $saveTo = 'uploads/cover/'.$img.'.'.$model->file_image->extension;
                if ($model->file_image->saveAs($saveTo, false));

                $model->image = $saveTo;
            }

                    $model->save();

            return $this->redirect(['view', 'idpost' => $model->idpost]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $idpost Idpost
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($idpost)
    {
        $this->findModel($idpost)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $idpost Idpost
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($idpost)
    {
        if (($model = Post::findOne(['idpost' => $idpost])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/post/ListCategory.php
<?php

use yii\grid\GridView;
use yii\widgets\ListView;
use yii\helpers\Html;

/** @var $this yii\web\View */
/** @var $category app\models\Category */
/** @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'List Category';
$this->params['breadcrumbs'][] = ['label' => 'Categorys', 'url' => ['/views/post/category']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="ListCategory">
    <h1><?= Html::encode($this->title) ?></h1>
        <?= 
        GridView::widget([
            'category.nama_category'
        ])
        ?>
</div>

views/post/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Category;
use app\models\Post;
use kartik\date\DatePicker;
use dosamigos\ckeditor\CKEditor;



/** @var yii\web\View $this */
/** @var app\models\Post $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="post-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'title')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'content')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'basic',
        'clientOptions' => [
        'allowedContent' => true,
    ],
    ]) ?>

    <?= $form->field($model, 'idcategory')->dropDownList(
    ArrayHelper::map(Category::find()->all(), 'idcategory', 'nama_category'),
    ['prompt' => '']) -> label('Category')?>

    <?= $form->field($model, 'file_image')->fileInput() ?>

    <?= $form->field($model, 'date')->hiddenInput() ->label(false) ?> 

    <?= $form->field($model, 'username')->hiddenInput(['maxlength' => true]) ->label(false) ?>

    <!-- <?= 
    $form->field($model, 'status')->dropDownList(
        ArrayHelper::map(Post::find()->select(['status'])->distinct()->all(), 'status', 'status'),
        ['prompt' => 'Select Status']) -> label(false) 
        ?> -->

    <?=
        $form->field($model, 'date_publish')->widget(DatePicker::classname(), [
            'options' => ['placeholder' => 'Masukkan Tanggal Publish'],
            'pluginOptions' => [
                'todayHighlight' => true,
                'autoclose' => true,
                'format' => 'yyyy-mm-dd',
            ]
        ]);
    ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\SearchPost $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="post-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'idpost') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'content') ?>

    <?= $form->field($model, 'idcategory') ?>

    <?= $form->field($model, 'date') ?>

    <?= $form->field($model, 'username') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/approve.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use app\models\User;
/* @var $this yii\web\View */
/* @var $searchModel app\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Approve Posts';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-approve">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'idpost',
            'title',
            [
                'attribute' => 'content',
                'format' => 'html',
                'value' => function ($model) {
                    return ($model->content);
                },
            ],
            'status',
            'username',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{approve} {view} {update} {delete}',
                'header' => 'AKSI',
                'headerOptions' => ['style' => 'width:11%', 'class' => 'text-center'],
                                'contentOptions' => ['class' => 'center'],
                'buttons' => [
                   'approve' => function ($url, $model) {
            return Html::a('Approve', ['approve', 'idpost' => $model->idpost], [
                'class' => 'btn btn-success btn-sm',
                'data' => [
                    'confirm' => 'Are you sure you want to approve this post?',
                    'method' => 'post',
                ],
            
            ]);
        },
    
                    'view' => function ($url, $model) {
            return Html::a('<svg aria-hidden="true" style="display:inline-block;font-size:inherit;height:1em;overflow:visible;vertical-align:-.125em;width:1.125em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M573 241C518 136 411 64 288 64S58 136 3 241a32 32 0 000 30c55 105 162 177 285 177s230-72 285-177a32 32 0 000-30zM288 400a144 144 0 11144-144 144 144 0 01-144 144zm0-240a95 95 0 00-25 4 48 48 0 01-67 67 96 96 0 1092-71z"/></svg>', ['view', 'idpost' => $model->idpost], ['class' => 'btn btn-primary btn-sm']);
        },
                    'update' => function ($url, $model) {
            return Html::a('<svg aria-hidden="true" style="display:inline-block;font-size:inherit;height:1em;overflow:visible;vertical-align:-.125em;width:1em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M498 142l-46 46c-5 5-13 5-17 0L324 77c-5-5-5-12 0-17l46-46c19-19 49-19 68 0l60 60c19 19 19 49 0 68zm-214-42L22 362 0 484c-3 16 12 30 28 28l122-22 262-262c5-5 5-13 0-17L301 100c-4-5-12-5-17 0zM124 340c-5-6-5-14 0-20l154-154c6-5 14-5 20 0s5 14 0 20L144 340c-6 5-14 5-20 0zm-36 84h48v36l-64 12-32-31 12-65h36v48z"/></svg>', ['update', 'idpost' => $model->idpost], ['class' => 'btn btn-warning btn-sm']);
        },
                    'delete' => function ($url, $model) {
            return Html::a('<svg aria-hidden="true" style="display:inline-block;font-size:inherit;height:1em;overflow:visible;vertical-align:-.125em;width:.875em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M32 464a48 48 0 0048 48h288a48 48 0 0048-48V128H32zm272-256a16 16 0 0132 0v224a16 16 0 01-32 0zm-96 0a16 16 0 0132 0v224a16 16 0 01-32 0zm-96 0a16 16 0 0132 0v224a16 16 0 01-32 0zM432 32H312l-9-19a24 24 0 00-22-13H167a24 24 0 00-22 13l-9 19H16A16 16 0 000 48v32a16 16 0 0016 16h416a16 16 0 0016-16V48a16 16 0 00-16-16z"/></svg>', ['delete', 'idpost' => $model->idpost], [
                'class' => 'btn btn-danger btn-sm',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this post?',
                    'method' => 'post',
                ],
                    ]);
                },
             ],
        ],
        ],
    ]); ?>
</div>

views/post/category.php
<?php
use yii\widgets\ListView;
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;

/** @var $this yii\web\View */
/** @var $category app\models\Category */
/** @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Category' .' '. $category->nama_category;
$this->params['breadcrumbs'][] = ['label' => 'Categorys', 'url' => ['/views/post/category']];
$this->params['breadcrumbs'][] = $this->title;
?>

<h1><?= Html::encode($this->title)?></h1>

<?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => function ($model) {
            return
                    '<div class="card">' .
                        Html::img(Yii::$app->request->baseUrl . '/' . $model->image, ['class' => 'card-img-top', 'style' => 'width:100%;height:150px; object-fit:cover;']) .
                    '<div class="card-body">' .
                     '<h5 class="card-title">' . Html::encode($model->title) . '</h5>' .
                    '<p class="card-text">' . HtmlPurifier::process($model->content) . '</p>' .
                    // '<p class="card-text"><small class="text-muted">Kategori: ' . Html::encode($model->category->category) . '</small></p>' .
                    '<p class="card-text"><small class="text-muted">Diposting oleh: ' . Html::encode($model->username) . ' pada ' . Yii::$app->formatter->asDate($model->date) . '</small></p>' .
                    Html::a('View details &raquo;', ['post/view', 'idpost' => $model->idpost], ['class' => 'btn btn-primary']) .
                    '</div>' .
                    '</div>';
        },
        'itemOptions' => ['class' => 'col-lg-4 mb-4'],
        'layout' => "<div class='row'>{items}</div>\n{pager}",
    ]); ?>

views/post/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Post $model */

$this->title = 'Create Post';
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/index.php
<?php

use app\models\Post;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use app\models\SearchPost;

/** @var yii\web\View $this */
/** @var app\models\SearchPost $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Blog';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Post', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
</div>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            //'idpost',
            'title:ntext',
            [
                'attribute' => 'content',
                'format' => 'html',
                'value' => function ($model) {
                    return ($model->content);
                },
            ],
            'date',
            'status',
            'date_publish',
            'username',
            'category.nama_category',
            [
                'attribute' => 'image',
                'format' => 'html',
                'value' => function ($model) {
                    return Html::img(Yii::$app->request->baseUrl . '/' . $model->image, ['class' => 'img-responsive', 'style' => 'width:150px']);
                },
            ],

            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Post $model) {
                    return Url::toRoute([$action, 'idpost' => $model->idpost]);
                 }
                ],
        ],
    ]); ?>


</div>

views/post/update.php
<?php

use yii\helpers\Html;
/** @var yii\web\View $this */
/** @var app\models\Post $model */

$this->title = 'Update Post: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'idpost' => $model->idpost]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="post-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use app\models\Post;
use dosamigos\ckeditor\CKEditor;

/** @var yii\web\View $this */
/** @var app\models\Post $model */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="post-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'idpost' => $model->idpost], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'idpost' => $model->idpost], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'idpost',
            [
                'attribute' => 'image',
                'format' => 'html',
                'value' => function ($model) {
                    return Html::img(Yii::$app->request->baseUrl . '/' . $model->image, ['class' => 'img-responsive', 'style' => 'width:350px']);
                },
            ],
            'title:ntext',
            [
                'attribute' => 'content',
                'format' => 'html',
                'value' => function ($model) {
                    return ($model->content);
                },
            ],
            'date',
            'status',
            'date_publish',
            'username',
            'category.nama_category',
        ],
        
    ]) ?>

</div>